name: greenpipes

channels:
  - defaults
  - conda-forge
  - bioconda
  - anaconda
  - r
dependencies:
  - python = 3.9.12
  - fastqc = 0.11.9
  - bedtools = 2.27.1
  - bowtie2 = 2.3.5.1
  - samtools = 1.10
  - deeptools = 3.5.1
  - subread = 2.0.0
  - sambamba = 0.6.9
  - seqtk = 1.4
  - pv = 1.6.6
  - pigz = 2.6
  - biopython = 1.81
  - termcolor = 2.3.0
  - pandas = 2.0.2
  - mygene = 3.2.2
  - pyfaidx = 0.7.2.1
  - upsetplot = 0.8.0
  - more-itertools = 9.1.0
  - setuptools = 67.7.2
  - idr = 2.0.4.2
  - trim-galore = 0.6.10
  - fastq-screen = 0.15.13
  - perl = 5.32.1
  - r = 4.3.0
  - homer
  - bwa = 0.7.17
