name: greenpipes
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - appdirs=1.4.4=pyhd3eb1b0_0
  - attrs=22.1.0=py310h06a4308_0
  - bedtools=2.31.0=hf5e1c6e_2
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - biopython=1.78=py310h7f8727e_0
  - biothings_client=0.2.6=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottleneck=1.3.5=py310ha9d4c09_0
  - bowtie=1.3.1=py310h4070885_4
  - bowtie2=2.5.1=py310h8d7afc0_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bwa=0.7.17=he4a0461_11
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hb05425b_5
  - cattrs=23.1.2=pyhd8ed1ab_0
  - certifi=2023.5.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=41.0.1=py310h774aba0_0
  - curl=7.88.1=h5eee18b_0
  - cutadapt=4.4=py310h4b81fae_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - deeptools=3.5.2=pyhdfd78af_1
  - deeptoolsintervals=0.1.9=py310h1425a21_4
  - dnaio=0.10.0=py310h4b81fae_3
  - exceptiongroup=1.0.4=py310h06a4308_0
  - expat=2.5.0=hcb278e6_1
  - fastq-screen=0.15.3=pl5321hdfd78af_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozendict=2.3.8=py310h2372a71_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_0
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - homer=4.11=pl5262h9f5acd7_8
  - htslib=1.17=h6bc39ce_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - idr=2.0.4.2=py310hd6be1da_9
  - isa-l=2.30.0=h7f8727e_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jpeg=9e=h5eee18b_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - ldc=1.28.1=hcf88599_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=7.88.1=h91b91d3_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=13.1.0=he5830b7_0
  - libgd=2.3.3=h6a678d5_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h5eee18b_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm12=12.0.1=hf817b99_2
  - libnghttp2=1.52.0=ha637b67_1
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.2.0=hecacb30_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.13=hd590300_5
  - lxml=4.9.1=py310h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - make=4.2.1=h1bed415_1
  - matplotlib=3.7.1=py310h06a4308_1
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - meme=4.11.2=py310pl5321h2cd2fb3_8
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - mygene=3.2.2=pyh5e36f6f_0
  - ncurses=6.4=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py310h757a811_1
  - numpy=1.23.5=py310hac523dd_0
  - numpy-base=1.23.5=py310h375b286_0
  - openjdk=11.0.13=h87a67e3_0
  - openssl=1.1.1u=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - pango=1.50.7=h05da053_0
  - pbzip2=1.1.13=0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.32.1=0_h5eee18b_perl5
  - perl-app-cpanminus=1.7046=pl5321hd8ed1ab_0
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-cgi=4.56=pl5321h031d066_1
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-encode=3.19=pl5321h166bdaf_0
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-gd=2.76=pl5321h5b5514e_1
  - perl-gdgraph=1.54=pl5321hdfd78af_1
  - perl-gdtextutil=0.86=pl5321h031d066_8
  - perl-html-parser=3.81=pl5321h4ac6f70_1
  - perl-html-tagset=3.20=pl5321hdfd78af_4
  - perl-html-template=2.97=pl5321hdfd78af_2
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=6.36=pl5321hdfd78af_0
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-mime-base64=3.16=pl5321h166bdaf_0
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-nowarnings=1.06=pl5321ha770c72_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_0
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-parser=2.44_01=pl5340hf309648_0
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - perl-xml-sax-expat=0.51=pl5321hd8ed1ab_0
  - perl-xml-simple=2.25=pl5321hdfd78af_2
  - perl-yaml=1.30=pl5321hdfd78af_0
  - pigz=2.6=h27cfd23_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.1.2=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkg-config=0.29.2=h1bed415_8
  - platformdirs=2.5.2=py310h06a4308_0
  - plotly=5.9.0=py310h06a4308_0
  - ply=3.11=py310h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pv=1.6.6=h470a237_0
  - py2bit=0.3.0=py310h4b81fae_8
  - pybigwig=0.3.22=py310h722e95c_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyfaidx=0.7.2.1=pyh7cba7a3_1
  - pyld=2.0.3=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysam=0.21.0=py310hff46b53_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-isal=1.1.0=py310h5eee18b_0
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310h06a4308_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0=py310h5eee18b_1
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - r-base=4.2.0=h1ae530e_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - requests-cache=1.1.0=pyhd8ed1ab_0
  - sambamba=1.0=h98b6b92_0
  - samtools=1.3.1=h9071d68_10
  - scipy=1.10.1=py310heeff2f4_1
  - seqtk=1.4=he4a0461_1
  - setuptools=67.8.0=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - subread=2.0.6=he4a0461_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tar=1.34=hb2e2bae_1
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py310h06a4308_0
  - termcolor=2.1.0=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tktable=2.10=h14c3975_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py310h5eee18b_0
  - trim-galore=0.6.10=hdfd78af_0
  - typing_extensions=4.6.3=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - ujson=5.4.0=py310h6a678d5_0
  - unzip=6.0=h611a1e1_0
  - upsetplot=0.8.0=pyhd8ed1ab_0
  - url-normalize=1.4.3=pyhd8ed1ab_0
  - urllib3=1.26.16=py310h06a4308_0
  - wget=1.21.4=h91b91d3_1
  - wheel=0.38.4=py310h06a4308_0
  - xopen=1.7.0=py310hff52083_2
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - dill==0.3.6
      - filetype==1.2.0
      - gtfparse==2.0.1
      - multiprocess==0.70.14
      - polars==0.18.7
      - pyqt5-sip==12.11.0
# prefix: /home/testing/anaconda3/envs/greenpipes
